### ISSUE TITLE
[1.18.1] crash when placing crystal

### ISSUE THREAD

**Issue by Bass2style** [Alexthw46/Indestructible#1]
Hi,

due to changes made a long time ago (in forge 39.0.45, where the Compound Tag as been removed), when you place the crystal, the game is crashing.

forge version : actually using 39.1.0, but any version since 39.0.45 should be affected
mod version : 1.18-0.2.2

crashlog : https://gist.github.com/Bass2style/343ea38e8fb1a74b39264ec6e6529de1

have a nice day.

**Comment by Alexthw46** [comment]
Uploaded 0.2.5 with the new save/load tag. (Give curse the time to approve it) No idea if it can be used on 1.18.2 too, i doubt that tbh.

**Comment by Bass2style** [comment]
got my 1.18.1 world back, thanks. xD

not tested on 1.18.2, a lot of mods in my modpack are still not updated for 1.18.2, but i can try on a random instance.

**Comment by Bass2style** [comment]
it's not working on 1.18.2, but if it can help, here is a crashlog : https://gist.github.com/Bass2style/6417b113d36f8cc81a30450dfce38780

**Comment by Alexthw46** [comment]
I expected that, thanks for the try, i only heard that few tag things changed so i'll update when i know enough about it. Hope there won't be issues in 1.18.1. I'm closing this for now
