### ISSUE TITLE
Crashes 1.18.2

### ISSUE THREAD

**Issue by krellim** [Alexthw46/Indestructible#2]
Had this in my 1.18.1 MC server, but recently updated (stability reasons for other mods) - unfortunately, this mod stopped working, and crashes the server if I force it to load: 1.18.2 - Forge 40.1

Hoping for a new version - Unbreaking III just doesn't cut it - I'm constantly having to make new tools :(

**Comment by Alexthw46** [comment]
Yes, due to the blacklist tag-based it needs a quick update. It's under review rn

**Comment by krellim** [comment]
Looks like it is working great - Issue can be closed
